apiVersion: v1
kind: Service
metadata:
  name: service-abctechnologies
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30080 
  selector:
    app: abctechnologies

